.TH CHOWN 1 "March 2026" "JLC Project" "User Commands"
.SH NAME
chown \- change file owner and group
.SH SYNOPSIS
.B chown
.I owner:group file
.SH DESCRIPTION
The
.B chown
utility changes the owner and group of the specified file.
.SH OPTIONS
None.
.SH USAGE
chown 1000:1000 myfile
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
Invalid arguments
.TP
.B 2
System error occurred
.SH AUTHOR
The JLC Project
.SH SEE ALSO
.BR chown (2)