.TH CHWN 1 "March 2026" "The JLC Project" "User Commands"
.SH NAME
chwn \- change file owner and group
.SH SYNOPSIS
.B chown
.I owner:group file
.SH DESCRIPTION
Change the owner and group of a file.
.SH OPTIONS
None.
.SH EXAMPLES
chwn 1000:1000 myfile
.SH AUTHOR
The JLC Project
.SH SEE ALSO
chmod(1), chgrp(1)