.TH JGREP 1 "March 2026" "The JLC Project" "User Commands"
.SH NAME
jgrep \- search for patterns in files
.SH SYNOPSIS
.B jgrep
.I pattern
.RI [ file ]
.SH DESCRIPTION
Search for lines containing a pattern in a file or standard input.
.SH OPTIONS
None.
.SH EXAMPLES
jgrep "hello" file.txt
.br
cat file.txt | jgrep "hello"
.SH AUTHOR
The JLC Project
.SH SEE ALSO
grep(1), fgrep(1)