.TH MOVE 1 "March 2026" "The JLC Project" "User Commands"
.SH NAME
move \- move or rename files
.SH SYNOPSIS
.B move
.I source destination
.SH DESCRIPTION
Move or rename files.
.SH OPTIONS
None.
.SH EXAMPLES
move file1.txt file2.txt
.br
move file.txt /home/user/
.SH AUTHOR
The JLC Project
.SH SEE ALSO
mv(1), cp(1)