.TH DUCT 1 "March 2026" "Version 1.0" "User Commands"
.SH NAME
duct \- print system architecture information (ultra-minimal version)
.SH SYNOPSIS
.B duct
.SH DESCRIPTION
.B duct
prints the system architecture information using direct system calls.
It is an ultra-minimal alternative to the arch command with no external dependencies.
.SH OPTIONS
None.
.SH EXAMPLES
.IP "duct"
Print system architecture information.
.SH AUTHOR
The JLC Project
.SH SEE ALSO
.BR arch (1)